### ISSUE TITLE
在swoole服务中, kafka生产数据报错

### ISSUE THREAD

**Issue by davisphper** [swoole/phpkafka#56]
* 你遇到了什么问题？
在swoole服务中, kafka生产数据报错

* Kafka 环境是自建还是云服务？
云服务, 版本1.1.1

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep longlang/phpkafka`

```
# 粘贴到这里
[1] 25961
PHP 7.2.21 (cli) (built: Aug 13 2019 13:30:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.21, Copyright (c) 1999-2018, by Zend Technologies

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.4.3
Built => Aug 13 2019 14:26:13
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
[1]+  Done                    /usr/bin/php72 -v

longlang/phpkafka                  v1.2.0          A kafka client. Support php-fpm and Swoole.
```

* 提供最小可复现代码：
```php
# 生产数据就这一个方法
public function producerForTimeOutNotLimit($value)
{
    if (empty($value) || !is_array($value)) throw new Exception('生产数据类型不可为空并且类型为数组');
    $value = json_encode($value);
    $config = new \longlang\phpkafka\Producer\ProducerConfig();
    $config->setBootstrapServer($this->config['service']);
    $config->setConnectTimeout(-1);
    $config->setUpdateBrokers(true);
    $producer = new \longlang\phpkafka\Producer\Producer($config);
    $producer->send($this->config['topic'], $value, '');
}
```

* 堆栈信息
```
[2021-09-26 11:33:13] dev.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught longlang\phpkafka\Exception\SocketException: Could not recv data from stream,  [0] in /data/wwwroot/abs/abs_gray3/vendor/longlang/phpkafka/src/Socket/SwooleSocket.php:128
Stack trace:
#0 /data/wwwroot/abs/abs_gray3/vendor/longlang/phpkafka/src/Client/SwooleClient.php(135): longlang\phpkafka\Socket\SwooleSocket->recv(4, -1)
#1 {main}
  thrown in /data/wwwroot/abs/abs_gray3/vendor/longlang/phpkafka/src/Socket/SwooleSocket.php:128
Stack trace:
#0 /data/wwwroot/abs/abs_gray3/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php(54): Laravel\Lumen\Application->handleShutdown()
#1 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}()
#2 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught longlang\\phpkafka\\Exception\\SocketException: Could not recv data from stream,  [0] in /data/wwwroot/abs/abs_gray3/vendor/longlang/phpkafka/src/Socket/SwooleSocket.php:128
Stack trace:
#0 /data/wwwroot/abs/abs_gray3/vendor/longlang/phpkafka/src/Client/SwooleClient.php(135): longlang\\phpkafka\\Socket\\SwooleSocket->recv(4, -1)
#1 {main}
  thrown at /data/wwwroot/abs/abs_gray3/vendor/longlang/phpkafka/src/Socket/SwooleSocket.php:128)
[stacktrace]
#0 /data/wwwroot/abs/abs_gray3/vendor/laravel/lumen-framework/src/Concerns/RegistersExceptionHandlers.php(54): Laravel\\Lumen\\Application->handleShutdown()
#1 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}()
#2 {main}
"}
```

**Comment by Yurunsoft** [comment]
用 Swoole 4.7试一下，首先排除疑似 Swoole 4.4 的问题，这个包不支持 Swoole 4.4 的。

云服务具体是哪家的？

**Comment by Yurunsoft** [comment]
用 Swoole 4.7试一下，首先排除疑似 Swoole 4.4 的问题，这个包不支持 Swoole 4.4 的。

云服务具体是哪家的？

**Comment by davisphper** [comment]
> 用 Swoole 4.7试一下，首先排除疑似 Swoole 4.4 的问题，这个包不支持 Swoole 4.4 的。
> 
> 云服务具体是哪家的？

腾讯云

**Comment by xinglxing** [comment]
> 已单独沟通解决

请教一下，这个问题怎么解决的？我现在也遇到这个问题了，版本也是 1.2.1

**Comment by a289459798** [comment]
我也遇到这个问题，1.2.1 , swoole版本是4.5.2
