### ISSUE TITLE
[10753] Unknown(10753) 错误

### ISSUE THREAD

**Issue by dygin** [swoole/phpkafka#86]
* 你遇到了什么问题？

longlang\phpkafka\Exception\KafkaErrorException: [10753] Unknown(10753)

* Kafka 环境是自建还是云服务？

自建/阿里云

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep longlang/phpkafka`

```
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.34-37+0~20230106.78+debian11~1.gbp1ece37, Copyright (c) 1999-2018, by Zend Technologies

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.10
Built => Jul  6 2022 13:15:54
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1n  15 Mar 2022
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

```

* 提供最小可复现代码：

```php
//很明显就是在connect的时候出现的问题
Notice: Uninitialized string offset: 0 in /data/web/w9/xgms_data_log/vendor/longlang/phpkafka/src/Protocol/Type/UVarInt.php on line 41
[WARNING] longlang\phpkafka\Exception\KafkaErrorException: [10753] Unknown(10753) in /data/web/w9/xgms_data_log/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php:385
Stack trace:
#0 /data/web/w9/xgms_data_log/app/Kernel/ClassMap/longlang/phpkafka/Client/SyncClient.php(198): longlang\phpkafka\Protocol\ErrorCode::check()
#1 /data/web/w9/xgms_data_log/app/Kernel/ClassMap/longlang/phpkafka/Client/SyncClient.php(103): longlang\phpkafka\Client\SyncClient->updateApiVersions()
#2 /data/web/w9/xgms_data_log/vendor/longlang/phpkafka/src/Client/SwooleClient.php(52): longlang\phpkafka\Client\SyncClient->connect()
#3 /data/web/w9/xgms_data_log/vendor/longlang/phpkafka/src/Broker.php(174): longlang\phpkafka\Client\SwooleClient->connect()
#4 /data/web/w9/xgms_data_log/vendor/longlang/phpkafka/src/Broker.php(156): longlang\phpkafka\Broker->getClientByBrokerId()
#5 /data/web/w9/xgms_data_log/vendor/longlang/phpkafka/src/Producer/Producer.php(160): longlang\phpkafka\Broker->getClient()
#6 /data/web/w9/xgms_data_log/vendor/longlang/phpkafka/src/Producer/Producer.php(55): longlang\phpkafka\Producer\Producer->sendBatch()
#7 /data/web/w9/xgms_data_log/app/Kernel/ClassMap/hyperf/kafka/src/Producer.php(69): longlang\phpkafka\Producer\Producer->send()
#8 [internal function]: Hyperf\Kafka\Producer->Hyperf\Kafka\{closure}()
#9 /data/web/w9/xgms_data_log/app/Kernel/ClassMap/hyperf/kafka/src/Producer.php(156): Closure->call()
#10 /data/web/w9/xgms_data_log/vendor/hyperf/utils/src/Functions.php(274): Hyperf\Kafka\Producer->Hyperf\Kafka\{closure}()
#11 /data/web/w9/xgms_data_log/app/Kernel/Context/Coroutine.php(62): call()
#12 {main}

```

**Comment by dygin** [comment]
#87
