### ISSUE TITLE
hyperf 接入kafka后遇到问题

### ISSUE THREAD

**Issue by 18767156402** [swoole/phpkafka#94]
* 你遇到了什么问题？
[10753] Unknown,trace:#0 /opt/www/vendor/longlang/phpkafka/src/Client/SyncClient.php(196): longlang\phpkafka\Protocol\ErrorCode::check()
#1 /opt/www/vendor/longlang/phpkafka/src/Client/SyncClient.php(103): longlang\phpkafka\Client\SyncClient->updateApiVersions()
#2 /opt/www/vendor/longlang/phpkafka/src/Client/SwooleClient.php(52): longlang\phpkafka\Client\SyncClient->connect()
#3 /opt/www/vendor/longlang/phpkafka/src/Broker.php(174): longlang\phpkafka\Client\SwooleClient->connect()
#4 /opt/www/vendor/longlang/phpkafka/src/Broker.php(156): longlang\phpkafka\Broker->getClientByBrokerId()
#5 /opt/www/vendor/longlang/phpkafka/src/Producer/Producer.php(160): longlang\phpkafka\Broker->getClient()
#6 /opt/www/vendor/hyperf/kafka/src/Producer.php(94): longlang\phpkafka\Producer\Producer->sendBatch()
#7 [internal function]: Hyperf\Kafka\Producer->Hyperf\Kafka\{closure}()

Warning: Uninitialized string offset 0 in /opt/www/vendor/longlang/phpkafka/src/Protocol/Type/UVarInt.php on line 41
PHP Warning:  Uninitialized string offset 0 in /opt/www/vendor/longlang/phpkafka/src/Protocol/Type/UVarInt.php on line 41

 sys.ERROR: ErrorException: Uninitialized string offset 0(0) in /opt/www/vendor/longlang/phpkafka/src/Protocol/Type/UVarInt.php:41
Stack trace:
#0 /opt/www/vendor/longlang/phpkafka/src/Protocol/Type/UVarInt.php(41): Hyperf\ExceptionHandler\Listener\ErrorExceptionHandler::Hyperf\ExceptionHandler\Listener\{closure}()
#1 /opt/www/vendor/longlang/phpkafka/src/Protocol/AbstractStruct.php(110): longlang\phpkafka\Protocol\Type\UVarInt::unpack()
#2 /opt/www/vendor/longlang/phpkafka/src/Protocol/ApiKeys.php(19): longlang\phpkafka\Protocol\AbstractStruct->unpack()
#3 /opt/www/vendor/longlang/phpkafka/src/Client/SwooleClient.php(126): longlang\phpkafka\Protocol\ApiKeys::createResponse()
#4 /opt/www/vendor/longlang/phpkafka/src/Client/SyncClient.php(195): longlang\phpkafka\Client\SwooleClient->recv()
#5 /opt/www/vendor/longlang/phpkafka/src/Client/SyncClient.php(103): longlang\phpkafka\Client\SyncClient->updateApiVersions()
#6 /opt/www/vendor/longlang/phpkafka/src/Client/Swool...

 RuntimeException: Partition 0 does not exists(0) in /opt/www/vendor/longlang/phpkafka/src/Consumer/OffsetManager.php:195
Stack trace:
#0 /opt/www/vendor/longlang/phpkafka/src/Consumer/Consumer.php(310): longlang\phpkafka\Consumer\OffsetManager->getFetchOffset()
#1 /opt/www/vendor/longlang/phpkafka/src/Consumer/Consumer.php(237): longlang\phpkafka\Consumer\Consumer->fetchMessages()
#2 /opt/www/vendor/longlang/phpkafka/src/Consumer/Consumer.php(215): longlang\phpkafka\Consumer\Consumer->consume()
#3 /opt/www/vendor/hyperf/kafka/src/ConsumerManager.php(150): longlang\phpkafka\Consumer\Consumer->start()
#4 /opt/www/vendor/hyperf/utils/src/Functions.php(82): Hyperf\Process\AbstractProcess@anonymous->Hyperf\Kafka\{closure}()
#5 /opt/www/vendor/hyperf/kafka/src/ConsumerManager.php(157): retry()
#6 /opt/www/vendor/hyperf/process/src/AbstractProcess.php(134): Hyperf\Process\AbstractProcess@anonymous->handle()

* Kafka 环境是自建还是云服务？

阿里云的kafka 

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep longlang/phpkafka`

```
# 粘贴到这里

![image](https://github.com/swoole/phpkafka/assets/7996875/35e396ed-ca3f-462f-953b-d7a1fb814932)

* 提供最小可复现代码：

```php
// 你的代码

![image](https://github.com/swoole/phpkafka/assets/7996875/f4081b56-a3ce-43fc-91be-8648cfaf2443)

**Comment by 18767156402** [comment]
最新包已经解决
